### ISSUE TITLE
DateTimePicker.Small Style Doesn't Work

### ISSUE THREAD

**Issue by fabraham-plexus** [ghost1372/HandyControls#147]
### Describe the bug

I want to use/see what the small style looks like for the `DateTimePicker` but it throws an exception during runtime. I'm unable to use any of the styles.

Exception:
```
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='Provide value on 'System.Windows.StaticResourceExtension' threw an exception.' Line number '54' and line position '68'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at RCTracker_WPF.Views.TicketOverviewPanel.InitializeComponent() in C:\Users\filjo.abraham\Documents\Projects\C#\RCTracker\RCTracker_WPF\Views\TicketOverviewPanel.xaml:line 1

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
Exception: Cannot find resource named 'DateTimePicker.Small'. Resource names are case sensitive.
```

Tested on both stable and unofficial release (HandyControls)

### Steps to reproduce the bug

```XAML
<hc:DateTimePicker Grid.Column="1" Grid.Row="0" Style="{StaticResource DateTimePicker.Small}"></hc:DateTimePicker>
```

### NuGet package version

HandyControls (Custom version) 3.3.11

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

October 2018 Update (17763)

**Comment by ghost1372** [comment]
report in original [repo](https://github.com/handyOrg/HandyControl/)

**Comment by Keeyahto** [comment]
Try `<hc:DateTimePicker Grid.Column="1" Grid.Row="0" Style="{hc:StaticResource DateTimePicker.Small}"></hc:DateTimePicker>`
